---

- name: output ec2 instances that have been provisioning
  ec2:
    region: us-east-1
    count_tag:
       - Name: application
  register: instances
    # - name: Terminate EC-2 instances
    #   ec2: 
    #     state: absent
    #     instance_ids: 