---



- name: Gather information about any instance with a tag key Name and value Example
  ec2_instance_info:
    region: us-east-1
    filters:
      "tag:Name": application
  register: instances_output
  delegate_to: localhost

- copy:
    content: "{{ instances_output }}"
    dest: /home/ansibleadm/output.json

# - name: debug out of instances
#   debug:
#     msg: "{{ item.instances.value.instance_id }}" 
#   loop: "{{ lookup('dict', instances_output) }}"
# - name: Print phone records
#   debug:
#     msg: "{{ instances_output.instance_id[0] }}"



  # - name: Terminate EC-2 instances
    #   ec2: 
    #     state: absent
    #     instance_ids: 