---



- name: Gather information about any instance with a tag key Name and value Example
  ec2_instance_info:
    region: us-east-1
    filters:
      "tag:Name": application
  register: instances_output
  delegate_to: localhost

# - copy:
#     content: "{{ instances_output }}"
#     dest: /home/ansibleadm/output.json

# - name: debug out of instances
#   debug:
#     msg: "{{ item.instances.value.instance_id }}" 
#   loop: "{{ lookup('dict', instances_output) }}"
- debug:
    msg: "{{ instances_output.instances[0].instance_id }}"



  # - name: Terminate EC-2 instances
    #   ec2: 
    #     state: absent
    #     instance_ids: 