---



- name: Gather information about any instance with a tag key Name and value Example
  ec2_instance_info:
    region: us-east-1
    filters:
      "tag:Name": application
  register: instances_output
- name: debug out of instances
  debug:
    msg: "{{ instances_output.instances.imagine_id }}" 
  
# - name: Print phone records
#   debug:
#     msg: "User {{ item.key.instance_id }}"
#   loop: "{{ lookup('dict', instances_output) }}"


  # - name: Terminate EC-2 instances
    #   ec2: 
    #     state: absent
    #     instance_ids: 