---



- name: Gather information about any instance with a tag key Name and value Example
  ec2_instance_info:
    region: us-east-1
    filters:
      "tag:Name": application
  register: instances

- name: debug out of instances
  debug:
    msg: "{{ instances }}" 
    # - name: Terminate EC-2 instances
    #   ec2: 
    #     state: absent
    #     instance_ids: 