---

- name: output ec2 instances that have been provisioning
    ec2:
        count_tag:
            Name: application
    register: instances
    # - name: Terminate EC-2 instances
    #   ec2: 
    #     state: absent
    #     instance_ids: 