- name: Running AWS Environment Setup role
  gather_facts: no
  connection: local
  collections:
    - amazon.aws
  hosts: localhost
  tasks:
  - name: Gather information about all availability zones
    amazon.aws.aws_az_info:
    # - include_role:
    #     name: aws_role