- name: Running AWS Environment Setup role
  gather_facts: yes 
  connection: local
#   collections:
#     - amazon.aws
  vars:
    aws_keypair: aws-keypair
    aws_region: us-east-1
    aws_ec2_ami: ami-098f16afa9edf40be  
    create_ec2: true
    aws_rds_port: 5432
    aws_rds_dbtype: postgres
  hosts: localhost
  tasks:
    - include_role:
        name: aws_role


 
