---
- name: "Getting VPC id... "
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc

- name: "Getting subnets id"
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc.vpcs[0].vpc_id }}"
  register: subnet

- name: "Getting SGroup id... "
  ec2_group_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc.vpcs[0].vpc_id }}"
      group-name: "mariadb_{{ aws_sgroup }}"
  register: group

- name: "Getting staging instance subnet id..."
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": staging.project
      instance-state-name: running
  register: ec2_staging_state

- name: "Getting production instance subnet id..."
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": production.project
      instance-state-name: running
  register: ec2_production_state

- name: Setting RDS facts
  set_fact:
    staging_subnet: "{{ ec2_staging_state['instances'][0].network_interfaces[0].subnet_id }}"
    production_subnet: "{{ ec2_production_state['instances'][0].network_interfaces[0].subnet_id }}"
    rds_subnet: "project"

- name: "Creating RDS Security group"
  rds_subnet_group:
    state: present
    region: "{{ region }}"
    name: "{{ rds_subnet }}"
    description: "DB sgroup for project"
    subnets:
       - "{{ staging_subnet }}"
       - "{{ production_subnet }}"

- name: "Staging mariadb rds instance..."
  rds:
    command: create
    instance_name: staging-mariadb
    db_engine: mariadb
    username: "{{ project_staging_rds_username }}"
    password: "{{ project_staging_rds_password }}"
    region: "{{ region }}"
    zone: "{{ region }}b"
    subnet: "{{ rds_subnet }}"
    instance_type: db.t2.micro
    size: "10"
    publicly_accessible: yes
    wait: yes
    wait_timeout: 600
    tags:
        Name: staging-project
  register: rds_staging_project

- name: "Production mariadb rds instance..."
  rds:
    command: create
    instance_name: production-mariadb
    db_engine: mariadb
    username: "{{ project_production_rds_username }}"
    password: "{{ project_production_rds_password }}"
    region: "{{ region }}"
    subnet: "{{ rds_subnet }}"
    zone: "{{ region }}c"
    instance_type: db.t2.small
    size: "10"
    publicly_accessible: yes
    wait: yes
    wait_timeout: 600
    tags:
        Name: production-project
  register: rds_production_project

- name: "Modifying rds instances... "
  rds:
    command: modify
    instance_name: "{{ item }}"
    region: "{{ region }}"
    subnet:
    vpc_security_groups: "{{ group['security_groups'][0].group_id }}"
  loop:
      - staging-project-mariadb
      - production-project-mariadb
