---
- name: "Getting VPC id... "
  ec2_vpc_net_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ aws_vpc_name }}"
  register: vpc

- name: "Getting subnets id"
  ec2_vpc_subnet_facts:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc.vpcs[0].vpc_id }}"
  register: subnet

- name: "Getting SGroup id... "
  ec2_group_facts:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc.vpcs[0].vpc_id }}"
      group-name: "rds"
  register: sgroup

- name: "Getting application instance subnet id..."
  ec2_instance_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": application
      instance-state-name: running
  register: ec2_subnet

- name: "Creating RDS Subnet group"
  rds_subnet_group:
    region: "{{ aws_region }}"
    name: "application"
    description: "DB sgroup for project"
    subnets:
       - "{{ subnet['subnets'][0].id }}"
       - "{{ subnet['subnets'][1].id }}"
       - "{{ subnet['subnets'][2].id }}"
       - "{{ subnet['subnets'][3].id }}"
       - "{{ subnet['subnets'][4].id }}"
       - "{{ subnet['subnets'][5].id }}"
    state: present

- name: "Application RDS instance 01"
  rds:
    command: create
    instance_name: "{{ aws_rds_01_name }}"
    db_engine: "{{ aws_rds_dbtype }}"
    username: "{{ application_rds_username }}"
    password: "{{ application_rds_password }}"
    region: "{{ aws_region }}"
    subnet: "application"
    zone: "{{ aws_region }}c"
    instance_type: "{{ aws_rds_instance_type }}"
    size: "10"
    publicly_accessible: no
    wait: yes
    wait_timeout: 600
    tags:
        Name: "{{ aws_rds_01_name }}"
  when: aws_rds_01_name is defined

- name: "Application RDS instance 02"
  rds:
    command: create
    instance_name: "{{ aws_rds_02_name }}"
    db_engine: "{{ aws_rds_dbtype }}"
    username: "{{ application_rds_username }}"
    password: "{{ application_rds_password }}"
    region: "{{ aws_region }}"
    subnet: "application"
    zone: "{{ aws_region }}c"
    instance_type: "{{ aws_rds_instance_type }}"
    size: "10"
    publicly_accessible: no
    wait: yes
    wait_timeout: 600
    tags:
        Name: "{{ aws_rds_02_name }}"
  when: aws_rds_02_name is defined

- name: "Updating RDS vpc security groups... "
  rds:
    command: modify
    instance_name: "{{ item }}"
    region: "{{ aws_region }}"
    subnet:
    vpc_security_groups: "{{ sgroup['security_groups'][0].group_id }}"
  loop:
      - "{{ aws_rds_01_name }}"
      - "{{ aws_rds_02_name }}"
