---
- name: "VPC creation"
  ec2_vpc_net:
    region: "{{ region }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ aws_vpc_block }}"
    state: present
  register: vpc

- name: "Subnets creation"
  ec2_vpc_subnet:
    region: "{{ region }}"
    az: "{{ region }}{{ item.az }}"
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ item.cidr }}"
    resource_tags:
        Name: Project Subnet
    wait: true
  register: vpc_subnets
  loop: "{{ aws_vpc_subnets }}"

- name: "Internet Gateway creation"
  ec2_vpc_igw:
   vpc_id: "{{ vpc.vpc.id }}"
   region: "{{ region }}"
   state: "present"
   tags:
     Name: "{{ igw_name }}"
  register: igw

- name: "Getting Route table facts"
  ec2_vpc_route_table_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc.vpc.id }}"      
  register: vpc_rtb

- name: "Routes and Subnets for VPC"
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    route_table_id: "{{ vpc_rtb.route_tables[0].id }}"
    tags:
      Name: "project_rtb"
    subnets: "{{ subnets_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    state: present
  register: vpc_routes
