---
- name: "Ensure aws-mngt keypair exist"
  ec2_key:
      name: "{{  keypair }}"
      region: "{{ region }}"
      state: present
  register: aws_mngt_keypair
  
- name: "Check for keypair locally"
  local_action: stat path="{{ keypair }}.pem"
  register: stat_key

- name: "Copy private key"
  local_action: copy content="{{ aws_mngt_keypair.key.private_key }}" dest="../{{ keypair }}.pem" mode=0400
  when: |
    aws_mngt_keypair.changed
