---
- name: "Ensure aws-mngt keypair exist"
  ec2_key:
      name: "{{  keypair }}"
      region: "{{ region }}"
      state: present
  register: aws_mngt_keypair

- name: "Check for keypair locally"
  command: stat path="{{ keypair }}.pem"
  delegate_to: localhost
  register: stat_key

- name: "Copy private key"
  command: copy content="{{ aws_mngt_keypair.key.private_key }}" dest="../{{ keypair }}.pem" mode=0400
  delegate_to: localhost
  when: aws_mngt_keypair.changed
